# Generated by Django 3.2.4 on 2021-07-13 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=200, null=True)),
                ('age', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, choices=[('head', 'head'), ('forearm', 'forearm'), ('palm', 'palm'), ('chest', 'chest'), ('pelvis', 'pelvis'), ('legs', 'legs')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.loc')),
            ],
        ),
        migrations.CreateModel(
            name='TestCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(blank=True, null=True, upload_to='')),
                ('audiodata', models.FileField(blank=True, null=True, upload_to='audio')),
                ('des', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('default', models.BooleanField(blank=True, null=True)),
                ('medTest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.medtest')),
            ],
        ),
        migrations.AddField(
            model_name='medtest',
            name='testcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.testcat'),
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('medtests', models.ManyToManyField(to='flashCardApp.MedTest')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.BooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.case')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.result')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='examtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.examtype'),
        ),
        migrations.AddField(
            model_name='case',
            name='result',
            field=models.ManyToManyField(through='flashCardApp.CaseRes', to='flashCardApp.Result'),
        ),
    ]
