# Generated by Django 3.2.3 on 2021-07-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApp', '0002_auto_20210716_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='medtest',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='testcat',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
