# Generated by Django 3.2.3 on 2021-07-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApp', '0003_auto_20210717_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagedata', models.ImageField(blank=True, null=True, upload_to='')),
                ('audiodata', models.FileField(blank=True, null=True, upload_to='audio')),
                ('des', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('default', models.BooleanField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.action')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('actions', models.ManyToManyField(to='flashCardApp.Action')),
            ],
        ),
        migrations.RemoveField(
            model_name='medtest',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='medtest',
            name='testcat',
        ),
        migrations.RemoveField(
            model_name='result',
            name='medTest',
        ),
        migrations.RemoveField(
            model_name='case',
            name='examtype',
        ),
        migrations.RemoveField(
            model_name='case',
            name='result',
        ),
        migrations.RemoveField(
            model_name='caseres',
            name='result',
        ),
        migrations.AlterField(
            model_name='loc',
            name='region',
            field=models.CharField(blank=True, choices=[('head and neck', 'head and neck'), ('upper limb', 'upper limb'), ('abdomen', 'abdomen'), ('chest', 'chest'), ('perineum', 'perineum'), ('lower limb', 'lower limb'), ('back', 'back')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
        migrations.DeleteModel(
            name='MedTest',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='TestCat',
        ),
        migrations.AddField(
            model_name='action',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.loc'),
        ),
        migrations.AddField(
            model_name='case',
            name='findings',
            field=models.ManyToManyField(through='flashCardApp.CaseRes', to='flashCardApp.Finding'),
        ),
        migrations.AddField(
            model_name='case',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.system'),
        ),
        migrations.AddField(
            model_name='caseres',
            name='finding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.finding'),
            preserve_default=False,
        ),
    ]
