# Generated by Django 3.2.3 on 2021-07-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApp', '0004_auto_20210718_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseres',
            name='req',
        ),
    ]
