# Generated by Django 3.2.3 on 2021-08-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApp', '0005_remove_caseres_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.loc'),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.system'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashCardApp.action'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='default',
            field=models.BooleanField(),
        ),
    ]
