# Generated by Django 3.2.3 on 2021-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashCardApp', '0006_auto_20210801_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='region',
            field=models.CharField(blank=True, choices=[('head and neck', 'head and neck'), ('left upper limb', 'left upper limb'), ('right upper limb', 'right upper limb'), ('abdomen', 'abdomen'), ('chest', 'chest'), ('perineum', 'perineum'), ('lower limb', 'lower limb'), ('back', 'back')], max_length=200, null=True),
        ),
    ]
